ARG SLURM_VERSION

FROM slurm-docker-cluster

LABEL org.opencontainers.image.title="slurmctl-with-nextflow-docker-cluster"

RUN set -ex \
    && yum makecache \
    && yum -y update \
    && yum -y install dnf-plugins-core \
    && yum config-manager --set-enabled powertools \
    && yum -y install java-17-openjdk \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN set -ex \
    && mkdir nextflow \
    && pushd nextflow \
    && curl -s https://get.nextflow.io | bash \
    && install -D -m755 ./nextflow /usr/local/bin/nextflow \
    && popd \
    && rm -rf nextflow

WORKDIR /pipelines

CMD ["do.nf"]

